import re
import sys
import json
import os
Json_file = {"____comment": "This file was generated by gxc-abigen. DO NOT EDIT - 2019-04-20T11:44:35",
  "version": "gxc::abi/1.0","types":[],"structs":[],"actions":[],"tables":[]}
class Struts:
	def	__init__(self, name, base):
		self.name = name
		self.base = base
		self.fields = []
	def toJson(self):
		return {"name":self.name,"base":self.base,"fields":self.fields}

class Actions:
	def __init__(self,name,type,pyable):
		self.name = name
		self.type = type
		self.payable = payable

	def toJson(self):
		return {"name":self.name,"type":self.type,"payable":self.payable}


with open(sys.argv[1],'r')as input_file:
	contents = input_file.read()
	stuc = re.compile(r'export function[^\n(]+\(.*\)')
	exprs = stuc.findall(contents)
	structs = []
	for expr in exprs:
		name = expr.split('(')[0].split(' ')[-1]
		paras = expr.split('(')[1][:-1]
		
		paras = re.sub(r' *', "", paras)
		paras = paras.split(',')
		st = {"name":name,"base":"","fields":[]}
		
		for para in paras:
			nt = para.split(':')
			tem = {"name":nt[0],"type":nt[1]}
			st["fields"].append(tem)
			#st["fields"].append({"name":tem[0],"type"tem[1]})
		structs.append(st)


	act = re.compile(r'export function[^\n(]+?\(.*action:.*\)')
	actions = act.findall(contents)

	ations = []
	for ac in actions:
		s = ac.split('(')[0].split(' ')[-1]
		print(s)
		ations.append({"name":s,"type":s,"payable":False})
	Json_file["structs"] = structs
	Json_file["actions"] = ations
with open(sys.argv[2],'w') as res:
	json.dump(Json_file,res,indent=4)
#os.system('mv '+sys.argv[1].split('.')[0]+'.json '+sys.argv[1].split('.')[0]+'.abi' )


